[tool.poetry]
name = "johnson"
version = "0.1.0"
description = ""
authors = ["sjlva <rtsilva@bi4all.pt>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
